// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Loading
export const SET_LOADING = "SET_LOADING";

// Web3
export const LOAD_ETHEREUM_BALANCE_SUCCESS = "LOAD_ETHEREUM_BALANCE_SUCCESS";
export const LOAD_ETHEREUM_BALANCE_FAIL = "LOAD_ETHEREUM_BALANCE_FAIL";
export const LOAD_WEB3_SUCCESS = "LOAD_WEB3_SUCCESS";
export const LOAD_WEB3_FAIL = "LOAD_WEB3_FAIL";
export const LOAD_NETWORK_SUCCESS = "LOAD_NETWORK_SUCCESS";
export const LOAD_NETWORK_FAIL = "LOAD_NETWORK_FAIL";
export const LOAD_GAS_SUCCESS = "LOAD_GAS_SUCCESS";
export const LOAD_GAS_FAIL = "LOAD_GAS_FAIL";
